version: '3.8'

services:
  ctfd:
    build: .
    user: root
    restart: always
    ports:
      - "8000:8000"
    environment:
      - UPLOAD_FOLDER=/var/uploads
      - DATABASE_URL=mysql+pymysql://ctfd:ctfd@db/ctfd
      - REDIS_URL=redis://cache:6379
      - WORKERS=1
      - LOG_FOLDER=/var/log/CTFd
      - ACCESS_LOG=-
      - ERROR_LOG=-
      - REVERSE_PROXY=true
    volumes:
      - /mnt/efs/ctfd_logs:/var/log/CTFd  # Store logs in EFS
      - /mnt/efs/ctfd_uploads:/var/uploads  # Store uploads in EFS
      - .:/opt/CTFd:ro  # Mount the application code as read-only
    depends_on:
      - db
    networks:
        default:
        internal:

  nginx:
    image: nginx:stable
    restart: always
    volumes:
      - ./conf/nginx/http.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
    depends_on:
      - ctfd

  db:
    image: mariadb:10.11
    restart: always
    environment:
      - MARIADB_ROOT_PASSWORD=ctfd
      - MARIADB_USER=ctfd
      - MARIADB_PASSWORD=ctfd
      - MARIADB_DATABASE=ctfd
      - MARIADB_AUTO_UPGRADE=1
    volumes:
      - /mnt/efs/mysql_data:/var/lib/mysql  # Store MySQL data in EFS
      - db_aria_logs:/var/lib/mysql/aria_log  # Local volume for Aria logs
    networks:
        internal:
    command: [mysqld, --character-set-server=utf8mb4, --collation-server=utf8mb4_unicode_ci, --wait_timeout=28800, --log-warnings=0]

  cache:
    image: redis:4
    restart: always
    volumes:
      - /mnt/efs/redis_data:/data  # Store Redis data in EFS
    networks:
        internal:

networks:
    default:
    internal:
        internal: true

volumes:
  db_aria_logs: